### ISSUE TITLE
Power flow analysis does not converge

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#69] opened 2017-10-20 15:03 UTC
```
INFO:root:Grid expansion for ding0_grids__3160.pkl
DEBUG:edisgo:Cumulative generator capacity (existing): 67196.6 kW
DEBUG:edisgo:==> MV generators
DEBUG:edisgo:64 generators imported.
DEBUG:edisgo:Capacities of 2 of 33 existing generators updated (220.6 kW).
DEBUG:edisgo:Generator 2428983 has no geom entry, EnergyMap's geom entry will be used.
DEBUG:edisgo:Generator 2452287 has no geom entry, EnergyMap's geom entry will be used.
DEBUG:edisgo:29 of 29 new generators added (43445.5 kW).
DEBUG:edisgo:==> LV generators
DEBUG:edisgo:1292 generators imported.
DEBUG:edisgo:Capacities of 2 of 191 existing generators (single units) updated (91.1 kW).
DEBUG:edisgo:Capacities of 1 of 460 existing generators (in 1 of 5 aggregated units) updated (4.3 kW).
DEBUG:edisgo:1 of 1 decommissioned generators in aggregated generators removed (265.0 kW).
DEBUG:edisgo:638 of 638 new generators added (638 single units and 0 units as aggregated generators) (11595.8 kW).
DEBUG:edisgo:Cumulative generator capacity (updated): 122289.0 kW
DEBUG:edisgo:Geo distance is zero, check objects' positions. Distance is set to 1m
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (1) in LV grid LVGrid_411526.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (13) exceeds the count of loads (1) in LV grid LVGrid_410867.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (10) exceeds the count of loads (1) in LV grid LVGrid_409785.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (1) in LV grid LVGrid_411100.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (2) in LV grid LVGrid_411050.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (1) in LV grid LVGrid_411664.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (1) in LV grid LVGrid_411784.
DEBUG:edisgo:No valid conn. target found for Generator_2452385. Connected to LVStation_412292.
DEBUG:edisgo:No valid conn. target found for Generator_2452462. Connected to LVStation_412292.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (2) exceeds the count of loads (1) in LV grid LVGrid_412292.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (1) in LV grid LVGrid_411773.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (2) in LV grid LVGrid_411792.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (2) in LV grid LVGrid_412556.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (1) in LV grid LVGrid_411856.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (3) in LV grid LVGrid_412429.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (2) in LV grid LVGrid_411848.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (1) in LV grid LVGrid_408775.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (1) in LV grid LVGrid_409426.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (2) in LV grid LVGrid_410351.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (3) exceeds the count of loads (1) in LV grid LVGrid_411925.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (10) exceeds the count of loads (5) in LV grid LVGrid_312027.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (10) exceeds the count of loads (1) in LV grid LVGrid_411875.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (3) in LV grid LVGrid_412366.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (1) in LV grid LVGrid_312094.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (1) in LV grid LVGrid_411972.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (3) exceeds the count of loads (1) in LV grid LVGrid_412334.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (1) in LV grid LVGrid_412518.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (4) in LV grid LVGrid_411695.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (1) in LV grid LVGrid_411496.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (2) exceeds the count of loads (1) in LV grid LVGrid_412662.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (5) in LV grid LVGrid_312130.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (9) exceeds the count of loads (1) in LV grid LVGrid_410392.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (1) in LV grid LVGrid_411230.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (3) in LV grid LVGrid_312208.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (2) in LV grid LVGrid_410556.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (3) in LV grid LVGrid_411999.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (6) in LV grid LVGrid_312303.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (3) in LV grid LVGrid_509923.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (4) in LV grid LVGrid_312307.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (2) in LV grid LVGrid_409989.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (3) exceeds the count of loads (1) in LV grid LVGrid_499363.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (1) in LV grid LVGrid_410901.
DEBUG:edisgo:No valid conn. target found for Generator_2069212. Connected to LVStation_408440.
DEBUG:edisgo:No valid conn. target found for Generator_2269644. Connected to LVStation_408440.
DEBUG:edisgo:No valid conn. target found for Generator_2429003. Connected to LVStation_408440.
DEBUG:edisgo:No valid conn. target found for Generator_2452526. Connected to LVStation_408440.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (1) in LV grid LVGrid_408440.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (2) in LV grid LVGrid_312430.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (3) exceeds the count of loads (2) in LV grid LVGrid_408960.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (9) exceeds the count of loads (1) in LV grid LVGrid_410154.
DEBUG:edisgo:No valid conn. target found for Generator_2069214. Connected to LVStation_411762.
DEBUG:edisgo:No valid conn. target found for Generator_2429002. Connected to LVStation_411762.
DEBUG:edisgo:No valid conn. target found for Generator_2429143. Connected to LVStation_411762.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (3) exceeds the count of loads (1) in LV grid LVGrid_411762.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (10) exceeds the count of loads (1) in LV grid LVGrid_410527.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (2) in LV grid LVGrid_410626.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (1) in LV grid LVGrid_409875.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (4) in LV grid LVGrid_312562.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (2) in LV grid LVGrid_408799.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (2) in LV grid LVGrid_411605.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (5) exceeds the count of loads (4) in LV grid LVGrid_313699.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (5) in LV grid LVGrid_313706.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (10) exceeds the count of loads (8) in LV grid LVGrid_313709.
DEBUG:edisgo:No valid conn. target found for Generator_1702099. Connected to LVStation_410198.
DEBUG:edisgo:No valid conn. target found for Generator_2429059. Connected to LVStation_410198.
DEBUG:edisgo:No valid conn. target found for Generator_2429182. Connected to LVStation_410198.
DEBUG:edisgo:No valid conn. target found for Generator_2429195. Connected to LVStation_410198.
DEBUG:edisgo:No valid conn. target found for Generator_2452473. Connected to LVStation_410198.
DEBUG:edisgo:No valid conn. target found for Generator_2452477. Connected to LVStation_410198.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (1) in LV grid LVGrid_410198.
DEBUG:edisgo:No valid conn. target found for Generator_2069209. Connected to LVStation_313728.
DEBUG:edisgo:No valid conn. target found for Generator_2429060. Connected to LVStation_313728.
DEBUG:edisgo:No valid conn. target found for Generator_2429084. Connected to LVStation_313728.
DEBUG:edisgo:No valid conn. target found for Generator_2452369. Connected to LVStation_313728.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (4) exceeds the count of loads (1) in LV grid LVGrid_313728.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (1) in LV grid LVGrid_412259.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (10) exceeds the count of loads (1) in LV grid LVGrid_412425.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (6) exceeds the count of loads (1) in LV grid LVGrid_411900.
DEBUG:edisgo:No valid conn. target found for Generator_1702102. Connected to LVStation_313893.
DEBUG:edisgo:No valid conn. target found for Generator_2452324. Connected to LVStation_313893.
DEBUG:edisgo:No valid conn. target found for Generator_2452451. Connected to LVStation_313893.
DEBUG:edisgo:No valid conn. target found for Generator_2452460. Connected to LVStation_313893.
DEBUG:edisgo:No valid conn. target found for Generator_2452461. Connected to LVStation_313893.
DEBUG:edisgo:No valid conn. target found for Generator_2452464. Connected to LVStation_313893.
DEBUG:edisgo:No valid conn. target found for Generator_2452475. Connected to LVStation_313893.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (4) in LV grid LVGrid_313893.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (9) exceeds the count of loads (5) in LV grid LVGrid_313896.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (8) exceeds the count of loads (1) in LV grid LVGrid_411123.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (2) exceeds the count of loads (1) in LV grid LVGrid_410932.
DEBUG:edisgo:The count of newly connected generators in voltage level 7 (7) exceeds the count of loads (1) in LV grid LVGrid_410952.
INFO:pypsa.pf:Slack bus for sub-network 0 is Bus_MVStation_3160
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots DatetimeIndex(['2011-12-04'], dtype='datetime64[ns]', freq='H')
INFO:pypsa.pf:Newton-Raphson solved in 5 iterations with error of 0.000001 in 0.225596 seconds
DEBUG:edisgo:==> Check MV/LV station load.
DEBUG:edisgo:==> 86 MV/LV station(s) has/have load issues.
DEBUG:edisgo:==> Check line load.
DEBUG:edisgo:==> 14 line(s) in LV grids has/have load issues.
DEBUG:edisgo:==> 74 line(s) in MV grid has/have load issues.
DEBUG:edisgo:==> 86 LV station(s) has/have been reinforced due to overloading issues.
DEBUG:edisgo:==> 88 branche(s) was/were reinforced due to over-loading issues.
DEBUG:edisgo:==> Run power flow analysis.
INFO:pypsa.pf:Slack bus for sub-network 0 is Bus_MVStation_3160
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots DatetimeIndex(['2011-12-04'], dtype='datetime64[ns]', freq='H')
WARNING:pypsa.pf:Warning, we didn't reach the required tolerance within 100 iterations, error is at 0.000001. See the section "Troubleshooting" in the documentation for tips to fix this. 
INFO:pypsa.pf:Newton-Raphson solved in 100 iterations with error of 0.000001 in 4.752252 seconds
Traceback (most recent call last):
  File "/home/guido/rli_local/eDisGo/edisgo/examples/example.py", line 59, in <module>
    network.reinforce()
  File "/home/guido/rli_local/eDisGo/edisgo/grid/network.py", line 276, in reinforce
    self, max_while_iterations=kwargs.get('max_while_iterations', 10))
  File "/home/guido/rli_local/eDisGo/edisgo/flex_opt/reinforce_grid.py", line 115, in reinforce_grid
    network.analyze()
  File "/home/guido/rli_local/eDisGo/edisgo/grid/network.py", line 271, in analyze
    raise ValueError("Power flow analysis did not converge.")
ValueError: Power flow analysis did not converge.
```

**Comment by gplssm** [comment] 2017-10-26 14:10
This cannot be reproduced with data version 20171025134031 for grid 3160 but convergence issues occur in other grids, i.e. 183, 178, 198, 188, 194

**Comment by gplssm** [comment] 2017-10-26 15:09
178: a line exists with 700 km length and R of 120 ohm
194: same thing here, a line with > 700 km and R > 120 ohm

I inspected grids 183,178,194 by

```
if any(sorted([_['line'].length >= 50 for _ in list(network.mv_grid.graph.lines())])):
    print("Before generators: ", list(network.mv_grid.graph.lines()))
```
after `Network.import_from_ding0()` and

```
if any(sorted([_['line'].length >= 50 for _ in list(network.mv_grid.graph.lines())])):
    print("After generators: ", list(network.mv_grid.graph.lines()))
```
after `network.import_generators()`.

I found out these long line exist beginning with the generators import.

**Comment by nesnoj** [comment] 2017-10-27 12:20
Fixed in c9ec13cf824817909ae43cedff053246392f82c4.
The problem: The genos of v0.3.0 are quite far away from the MVGD of dingo v0.2.10 :fist_oncoming:  #76.

I added a function which checks whether 1 random LV and 1 random MV geno are both located in the MVGD. If not, it throws an exception.. this way we can detect if we use data from 2 different versions ;).

BTW: I was wondering why it took so long to connect the MV genos but if they are >700km away the buffer had to increase...and increase...and increase...

**Closed by nesnoj** 2017-10-27 12:20 UTC
Labels: bug

**Comment by gplssm** [comment] 2017-10-27 12:38
With the correct new Ding0 dataset of `run_id` "20171027113743" I can reproduce the error with grid 3160.
That high values for length or R and X are not present there.

**Comment by nesnoj** [comment] 2017-10-27 12:47
What do you mean by "reproduce"?
Is the new exception raised?

**Comment by nesnoj** [comment] 2017-10-27 13:19
I gave it a try and pypsa's max. of 100 iterations is exceeded.
Dunno what's the reason here...

**Comment by gplssm** [comment] 2017-10-27 13:40
> What do you mean by "reproduce"?
> Is the new exception raised?
This was actually, already outdated... It intended only to say that the error is present again with the newly generated dataset.

**Comment by nesnoj** [comment] 2017-10-27 13:48
ok

**Comment by gplssm** [comment] 2017-10-27 14:26
I diggin further....
